### ISSUE TITLE
WP-Vagrant doesn't work on a Windows host

### ISSUE THREAD

**Issue by anugupta** [digitalquery/wp-vagrant#13]
Lots of different issues, needs to be worked through.

**Comment by denizdogan** [comment]
Are there still outstanding issues on Windows?

**Comment by anugupta** [comment]
@denizdogan almost certainly - I don't use Windows, and I don't have a Windows PC to test on, so I can't say for certain, but there's been no work to address whatever issues exist  - someone had told me that some things didn't work, but i got no details.

**Comment by pjcunningham** [comment]
This worked for me without any issues using Windows 7 (64) with Cygwin (64).

**Comment by anugupta** [comment]
@pjcunningham Thanks for that - good to know!
