### ISSUE TITLE
Is there a 32 bit version?

### ISSUE THREAD

**Issue by jalevin** [digitalquery/wp-vagrant#16]
I have a laptop with a well known issue for running with VT-D enabled thus I cannot run 64 bit virtual OS. Is there a 32 bit version I can substitute for?

**Comment by anugupta** [comment]
You could always try building your own vagrant box and then changing the Vagrantfile to point at your new box.

Take a look at `bootstrap.sh`, and you'll see the packages that are in the base box:

```
# all this provisioning has been moved into the base box setup (digitalquery/wpvagrant)

# apt-get update && apt-get upgrade -y
# apt-get install -qy nginx php5 php5-fpm php5-apcu php5-gd php5-mysql php5-cgi php5-cli php5-curl php5-xdebug phpunit vim git-core mysql-server-5.5 mysql-client curl byobu
```

So, get a vagrant instance configured with the above packages installed and then package it up with `vagrant package` (https://docs.vagrantup.com/v2/cli/package.html). That's probably how I'd approach it
