### ISSUE TITLE
Problem with php mbstring extension

### ISSUE THREAD

**Issue by dumday** [digitalquery/wp-vagrant#19]
I tried to use functions like `mb_strtoupper`, `mb_strtolower` ... and I realized that the mbstring extension was not originally loaded. I tried to change the php.ini ( added `extension=mbstring.so` and ran `vagrant provision` ) then I realized that the **mbstring.so** file couldn't be found in any folders inside **\usr\lib\php**. I tried to install the extension through `apt-get` but it said the package couldn't be found. Please help me.

Thanks in advance.

**Comment by anugupta** [comment]
I  just experienced the same problem. i've pushed an update that installs the mbstring extension, so pull that and then rerun `vagrant provision`.

Alternatively (and temporarily), you can `vagrant ssh` and then:
````
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install php-mbstring php7.0-mbstring
````

**Comment by dumday** [comment]
Thank you very much :+1:

**Comment by anugupta** [comment]
@dumday Actually depending on your PHP version, you need to slightly change the above to match the version of PHP:

`sudo apt-get install php5.5-mbstring` or 
`sudo apt-get install php5.6-mbstring`
