### ISSUE TITLE
Site hangs when changing hostname

### ISSUE THREAD

**Issue by niklasquitzau** [digitalquery/wp-vagrant#25]
When doing `vagrant up` with the default settings everything works fine, however when I am attempting to change the hostname from the default `wpvagrant.dev` the site just hangs. It still loads the title in the tab in Chrome and Safari, but Chrome just keeps loading and says "Connecting". WP-admin is also inaccessible. I have also changed the custom hostname in the Vagrantfile but to no prevail. I've also tried changing the IP address but no go. I haven't changed anything else, and the error occurs when doing a fresh WP install.

Any suggestions?

**Comment by anugupta** [comment]
Did you change the hostname setting in `wp-vagrant/settings.sh`? It should match whatever you used in your `Vagrantfile`

**Comment by niklasquitzau** [comment]
Yes, I've changed in the settings.sh also, but it's still not working.

**Comment by anugupta** [comment]
Did you change the hostname in the `VagrantFile` and `settings.sh` before you did your first `vagrant up`? If not, did you run `vagrant provision` afterwards?

**Comment by niklasquitzau** [comment]
Yes, I tried both I'm afraid. And I checked `/etc/hosts` and the host was indeed updated to the hostname I provided. I also tried with a fresh install and tried destroying the box and `vagrant up` also with `--provision`. Seems strange.

**Comment by anugupta** [comment]
That's very odd and quite hard to diagnose from here.

Is the network stack working correctly? Can you ping the new hostname and get a response? What does `vagrant ssh-config` show? Can you ping the IP address? Can you browse to the IP address with Chrome?

**Comment by anugupta** [comment]
Closing as no response
