### ISSUE TITLE
Update base image to use Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by anugupta** [digitalquery/wp-vagrant#30]

**Comment by hesyifei** [comment]
In this forked repo https://github.com/TheStanfordDaily/wp-vagrant, I use the official [Ubuntu 18.04 box](https://app.vagrantup.com/ubuntu/boxes/bionic64) as `config.vm.box` and then install PHP (also update to support PHP 7.1 to 7.3) and other components during the first boot with provisioning (based on the scripts in https://github.com/paulherron/vagrant_precise32_nginx_mysql_php-fpm).

**Comment by anugupta** [comment]
Thanks for this - I'm incredibly busy right now, but will try and look at this in the next couple of weeks and merge it in.  Appreciate what you've done 👍

**Comment by anugupta** [comment]
Closed by
